### ISSUE TITLE
Error stopping the server programmatically

### ISSUE THREAD

**Issue by marcospassos** [belgattitude/pjbserver-tools#9] opened 2019-02-13 13:53 UTC
Hello,

I'm using the standalone server for testing purposes but it fails when the test ends:

```php
class ExampleTest extends TestCase
{
    public static function setUpBeforeClass() : void
    {
        // Start the server
        $params = (include __DIR__ . '/../resources/config/pjbserver.config.php.dist');

        $config = new StandaloneServer\Config($params);
        self::$server = new StandaloneServer($config);

        if (!self::$server->isProcessRunning()) {
            self::$server->start();
        }
    }

    public static function tearDownAfterClass() : void
    {
        self::$server->stop(true);
    }
}
```

Error:
```
PHP Notice:  fwrite(): send of 5 bytes failed with errno=32 Broken pipe in vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/ChunkedSocketChannel.php on line 54
```

Stack trace:
```
PHP   1. {main}() vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() vendor/phpunit/phpunit/phpunit:61
PHP   3. PHPUnit\TextUI\Command->run() vendor/phpunit/phpunit/src/TextUI/Command.php:162
PHP   4. PHPUnit\TextUI\TestRunner->doRun() vendor/phpunit/phpunit/src/TextUI/Command.php:206
PHP   5. Soluble\Japha\Bridge\Driver\Pjb62\PjbProxyClient::unregisterInstance() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/PjbProxyClient.php:0
PHP   6. Soluble\Japha\Bridge\Driver\Pjb62\Protocol->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/PjbProxyClient.php:568
PHP   7. Soluble\Japha\Bridge\Driver\Pjb62\SocketHandler->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/Protocol.php:330
PHP   8. Soluble\Japha\Bridge\Driver\Pjb62\ChunkedSocketChannel->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/SocketHandler.php:99
PHP   9. Soluble\Japha\Bridge\Driver\Pjb62\ChunkedSocketChannel->keepAliveSC() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/ChunkedSocketChannel.php:82
PHP  10. Soluble\Japha\Bridge\Driver\Pjb62\ChunkedSocketChannel->fwrite() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/EmptyChannel.php:140
PHP  11. fwrite() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/ChunkedSocketChannel.php:54
```

**Comment by marcospassos** [comment] 2019-02-13 14:03
Sometimes I get a different error:

```
PHP Notice:  Uninitialized string offset: 6 in vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/EmptyChannel.php on line 126

PHP Stack trace:
PHP   1. {main}() vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() vendor/phpunit/phpunit/phpunit:61
PHP   3. PHPUnit\TextUI\Command->run() vendor/phpunit/phpunit/src/TextUI/Command.php:162
PHP   4. PHPUnit\TextUI\TestRunner->doRun() vendor/phpunit/phpunit/src/TextUI/Command.php:206
PHP   5. Soluble\Japha\Bridge\Driver\Pjb62\PjbProxyClient::unregisterInstance() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/PjbProxyClient.php:0
PHP   6. Soluble\Japha\Bridge\Driver\Pjb62\Protocol->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/PjbProxyClient.php:568
PHP   7. Soluble\Japha\Bridge\Driver\Pjb62\SocketHandler->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/Protocol.php:330
PHP   8. Soluble\Japha\Bridge\Driver\Pjb62\ChunkedSocketChannel->keepAlive() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/SocketHandler.php:99
PHP   9. Soluble\Japha\Bridge\Driver\Pjb62\ChunkedSocketChannel->checkE() vendor/soluble/japha/src/Soluble/Japha/Bridge/Driver/Pjb62/ChunkedSocketChannel.php:83
```

**Comment by belgattitude** [comment] 2019-02-18 07:12
hey Marcos, thanks for reporting.  I'm quite busy right now but at first look you can ignore those errors.

if you want to dig down, I guess it's because of register_shutdown_function in soluble-japha client. when the script ends the client tries to close its connection to the server, flushing buffers.... if the server have been halted it should fail and produce warnings. 

I think you can close the client before stopping the server.  it's a singleton instance. not that I'm not too happy with this but it was designed originally like that. 

hope it helps.  and let me know what version of client you're using

**Comment by marcospassos** [comment] 2019-02-18 12:10
First of all, thank you so much for finding the time to reply to the issue, even being busy. I understand how hard it is sometimes to find time to dedicate to OSS initiatives.

> I think you can close the client before stopping the server. it's a singleton instance. not that I'm not too happy with this but it was designed originally like that

I tried that, and it worked, thank you. However, in the long run, I don't think it is a good solution as it exposes implementation details that I should never have to know.

For someone else facing the same issue, follows how to fix it for now:

```php
PjbProxyClient::unregisterInstance();
$server->stop();
```

**Comment by belgattitude** [comment] 2019-02-18 15:29
marcos, looks good to me.

Wasn't aware of people using this, but just released a 3.0.0 version: https://github.com/belgattitude/pjbserver-tools/releases/tag/3.0.0

BTW there's many ways to launch a bridge server for tests. FYI, for travis, you can have a look here:

https://github.com/belgattitude/soluble-japha/blob/master/.travis/launch_javabridge_server.sh

and the related gradle file where I set up dependencies:

https://github.com/belgattitude/soluble-japha/blob/master/.travis/init.travis.gradle

The webapprunner approach is quite easy and is more efficient than the standalone server. You can have a try too. I'm not sure to maintain the pjbserver-tools long, I'm not using it anymore.

Thanks for your thanks :)

**Closed as completed by belgattitude** 2019-02-18 15:29 UTC

**Comment by marcospassos** [comment] 2019-02-18 15:35
Sébastien, this library is perfect for functional tests relying on the java bridge. We're heavily using both in a relevant project.

Thank you for quickly solving the issue!

**Comment by marcospassos** [comment] 2019-02-20 15:46
Hey @belgattitude,

As feedback, we tried the solutions you recommended, and the standalone server provides by far a smoother start for beginners. In fact, this is our choice for testing purpose, due to the simplicity to start the server with zero configuration, no build steps, etc.

Could you consider to not deprecate it?

**Comment by belgattitude** [comment] 2019-02-20 17:03
Why not ? I don't think there will be a lot of changes, and the latest version is tested with 7.3. 

So it's fine for me. Don't hesitate to make any P/R, I'll gladly include them.

**Comment by marcospassos** [comment] 2019-02-20 17:13
Sure, I can't see new features either. The facility of starting the server just before the unit test is very appealing :)
